# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(458, 367)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 120, 311, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.userText = QtWidgets.QLabel(self.formLayoutWidget)
        self.userText.setObjectName("userText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userText)
        self.userNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userNameInput.setObjectName("userNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameInput)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwordInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
        self.loginBtn = QtWidgets.QPushButton(Form)
        self.loginBtn.setGeometry(QtCore.QRect(100, 270, 93, 28))
        self.loginBtn.setObjectName("loginBtn")
        self.resetBtn = QtWidgets.QPushButton(Form)
        self.resetBtn.setGeometry(QtCore.QRect(250, 270, 93, 28))
        self.resetBtn.setObjectName("resetBtn")
        self.titleLogin = QtWidgets.QLabel(Form)
        self.titleLogin.setGeometry(QtCore.QRect(110, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.titleLogin.setFont(font)
        self.titleLogin.setObjectName("titleLogin")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.userText.setText(_translate("Form", "USER:"))
        self.label_2.setText(_translate("Form", "PASSWORD:"))
        self.loginBtn.setText(_translate("Form", "Login"))
        self.resetBtn.setText(_translate("Form", "Reset"))
        self.titleLogin.setText(_translate("Form", "AI Algorithm Box"))


