# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_v2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_login_window = QtWidgets.QFrame(self.centralwidget)
        self.left_login_window.setGeometry(QtCore.QRect(140, 130, 361, 541))
        self.left_login_window.setStyleSheet("#left_login_window{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.151882, y1:0.125, x2:0.161686, y2:1, stop:0 rgba(0, 59, 167, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"")
        self.left_login_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_login_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_login_window.setObjectName("left_login_window")
        self.titleLogin = QtWidgets.QLabel(self.left_login_window)
        self.titleLogin.setGeometry(QtCore.QRect(60, 100, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(24)
        self.titleLogin.setFont(font)
        self.titleLogin.setObjectName("titleLogin")
        self.right_login_window = QtWidgets.QFrame(self.centralwidget)
        self.right_login_window.setGeometry(QtCore.QRect(500, 180, 370, 440))
        self.right_login_window.setMinimumSize(QtCore.QSize(370, 440))
        self.right_login_window.setStyleSheet("#right_login_window{\n"
"\n"
"    border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 0;\n"
"border-bottom-left-radius: 0;;\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.right_login_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_login_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_login_window.setObjectName("right_login_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_login_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.right_login_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resources/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./resources/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.right_login_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.userNameInput = QtWidgets.QLineEdit(self.frame)
        self.userNameInput.setObjectName("userNameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userNameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.frame)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userText = QtWidgets.QLabel(self.frame)
        self.userText.setObjectName("userText")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userText)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.right_login_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginBtn = QtWidgets.QPushButton(self.frame_3)
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.resetBtn = QtWidgets.QPushButton(self.frame_3)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout.addWidget(self.resetBtn)
        self.verticalLayout.addWidget(self.frame_3)
        self.right_login_window.raise_()
        self.left_login_window.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLogin.setText(_translate("MainWindow", "AI Algorithm Box"))
        self.label_2.setText(_translate("MainWindow", "PASSWORD:"))
        self.userText.setText(_translate("MainWindow", "USER:"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
